import {JSDOM} from 'jsdom';
import React from 'react';
import * as JSXR from 'react/jsx-runtime';
import {createRoot} from 'react-dom/client';
import fs from 'fs';
const d=JSON.parse(fs.readFileSync((process.env.BH10_COPIA||'/home/claude/copia/BH10_copia_completa_2026-09-06.json'),'utf8'));
const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'https://bh10group.com/app/',pretendToBeVisual:true});
for(const k of ['window','document','navigator','localStorage','sessionStorage','HTMLElement','Node','CustomEvent','Event','FileReader','Blob','URL','atob','btoa']){try{globalThis[k]=dom.window[k]??globalThis[k];}catch(e){}}
globalThis.window=dom.window;
window.matchMedia=()=>({matches:false,addListener(){},removeListener(){},addEventListener(){},removeEventListener(){}});
window.requestAnimationFrame=cb=>setTimeout(cb,0);globalThis.requestAnimationFrame=window.requestAnimationFrame;
window.cancelAnimationFrame=()=>{};globalThis.cancelAnimationFrame=()=>{};
class RO{observe(){}unobserve(){}disconnect(){}}window.ResizeObserver=RO;globalThis.ResizeObserver=RO;
window.IntersectionObserver=class{observe(){}unobserve(){}disconnect(){}};window.scrollTo=()=>{};
window.confirm=()=>true;window.prompt=()=>'';window.alert=()=>{};
window.__BH10_R=React;window.__BH10_JSX=JSXR;window.__BH10_STANDALONE=true;
window.BH10_EMPRESA={sub:'',nombre:'BIG HOUSE 2010'};window.BH10_ROL='admin';window.BH10_PERMISOS=null;
const nube={};for(const k of Object.keys(d.claves))nube[k]=d.claves[k];
const escrituras=[];window.storage={get:async k=>nube[k]!==undefined?{key:k,value:nube[k]}:null,set:async(k,v)=>{escrituras.push(k);nube[k]=String(v);return{key:k,value:v}},delete:async k=>{delete nube[k];return{key:k}},list:async p=>({keys:Object.keys(nube).filter(k=>!p||k.startsWith(p))}),getStatus:()=>({fase:'ok',error:'',ultimaEscritura:Date.now(),errorEscritura:'',pendientes:0,conflicto:null})};
const {default:App}=await import('/home/claude/web_subir/app/assets/bh10-APPV314.js');
createRoot(document.getElementById('root')).render(React.createElement(App));
const E=ms=>new Promise(r=>setTimeout(r,ms));
const oe=console.error;console.error=()=>{};
await E(1200);
const click=(t,exacto)=>{const b=[...document.querySelectorAll('button')].find(x=>exacto?x.textContent.trim()===t:x.textContent.includes(t));if(b)b.click();return !!b;};
const bots=()=>[...document.querySelectorAll('button')].map(b=>b.textContent.trim()).filter(t=>t&&t.length<50);
// nube completa: ¿pantalla de custodia? mostrar texto si no hay pestañas
if(!bots().some(t=>t.includes('Facturas')))console.log('PANTALLA PREVIA:',document.getElementById('root').textContent.slice(0,300));
click('Facturas');await E(900);
console.log('── PAGAR: clic al primer Pagar');
click('Pagar',true);await E(700);
console.log('  texto tras Pagar:',document.getElementById('root').textContent.slice(0,0)|| '');
const dlg=[...document.querySelectorAll('div')].map(x=>x.textContent).sort((a,b)=>a.length-b.length).find(t=>t.includes('Pagar')&&t.length<600);
console.log('  diálogo:',(dlg||'(¿sin diálogo?)').slice(0,300));
console.log('  escrituras tras Pagar:',escrituras);
const fc=JSON.parse(nube['bh10-fc-v3']);
const conPagoNuevo=fc.filter(i=>(i.pagos||[]).length>0).length;
console.log('  facturas con pagos ahora:',conPagoNuevo);
console.log('  inputs visibles:',document.querySelectorAll('input').length);
console.log('  ¿texto Confirmar/Toca?',/Toca de nuevo|Confirmar/.test(document.getElementById('root').textContent));
console.log('── REMESAS');
click('🏦 Remesas');await E(1000);
console.log('  botones:',bots().slice(0,30).join(' | ').slice(0,700));
console.log('── CONTRATOS');
click('Contratos');await E(900);
console.log('  botones:',bots().slice(0,30).join(' | ').slice(0,700));
console.log('── CERTIFICAR (primer contrato)');
click('📋 Certificar');await E(900);
console.log('  inputs:',document.querySelectorAll('input').length,'· botones:',bots().filter(t=>!t.includes('Pagar')).slice(0,25).join(' | ').slice(0,600));
const dtxt=document.getElementById('root').textContent;
console.log('  ¿form certificación?',/[Cc]ertificaci|porcentaje|importe a certificar/.test(dtxt));
console.log('  CERT inputs:',[...document.querySelectorAll('input')].slice(-8).map(i=>i.type+':'+(i.placeholder||i.value||'').slice(0,18)).join(' | '));
console.log('── NÓMINAS → REMESAR');
click('Nóminas');await E(1000);
click('💶 Remesar');await E(1000);
console.log('  botones remesa:',bots().filter(t=>!/Panel|Facturas|Contratos|Nóminas|Seguros|Ajustes|Pagar/.test(t)).slice(0,25).join(' | ').slice(0,700));
console.log('  inputs remesa:',[...document.querySelectorAll('input')].slice(0,10).map(i=>i.type+':'+(i.placeholder||String(i.value).slice(0,14))).join(' | '));
console.log('  texto:',document.getElementById('root').textContent.replace(/\s+/g,' ').slice(400,1100));
console.log('── CERT DEPURACIÓN');
click('Contratos');await E(800);
click('📋 Certificar');await E(700);
const pon=(el,val)=>{const prev=el.value;const st=Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set;st.call(el,val);if(el._valueTracker)el._valueTracker.setValue(prev);el.dispatchEvent(new dom.window.Event('input',{bubbles:true}));};
const pct=[...document.querySelectorAll('input')].find(i=>(i.placeholder||'').includes('Ej: 20%'));
console.log('  ¿input %?',!!pct);
if(pct)pon(pct,'10');await E(300);
const modal=[...document.querySelectorAll('div')].filter(x=>x.textContent.includes('quieres certificar')).sort((a,b)=>a.textContent.length-b.textContent.length)[0];
console.log('  modal tras poner 10%:',modal?modal.textContent.replace(/\s+/g,' ').slice(0,420):'(?)');
click('Generar factura',true);await E(350);
const t=document.getElementById('root').textContent;
console.log('  toast inmediato:',(t.match(/(⚠|✓|⛔)[^📊]{3,110}/)||['ninguno'])[0].replace(/\s+/g,' ').slice(0,130));
await E(900);
console.log('  ¿modal sigue?',document.getElementById('root').textContent.includes('quieres certificar'));
console.log('── CERT ITERANDO CONTRATOS');
for(let nC=0;nC<6;nC++){
  const certs=[...document.querySelectorAll('button')].filter(x=>x.textContent.includes('📋 Certificar'));
  if(!certs[nC]){console.log('  (no hay más)');break;}
  certs[nC].click();await E(600);
  const pct=[...document.querySelectorAll('input')].find(i=>(i.placeholder||'').includes('Ej: 20%'));
  if(pct)pon(pct,'10');await E(250);
  click('Generar factura',true);await E(400);
  const tt=document.getElementById('root').textContent;
  console.log('  contrato',nC,'→ escrituras:',escrituras.length,'· ¿modal?',tt.includes('quieres certificar'));
  await E(600);
  click('Cancelar',true);await E(300);
}
console.log('── EDITOR C34 NÓMINAS');
click('Nóminas');await E(900);
click('💶 Remesar');await E(800);
click('Editar importes y generar C34');await E(1000);
console.log('  botones editor SIN FILTRO:',bots().slice(0,40).join(' | ').slice(0,900));
console.log('  inputs editor:',document.querySelectorAll('input').length);
console.log('── PROVEEDORES (ficha)');
click('Facturas');await E(700);click('🏪 Proveedores');await E(900);
console.log('  botones:',bots().filter(t=>!/Panel$|Facturas|Contratos|Nóminas|Seguros|Ajustes|Pagar/.test(t)).slice(0,20).join(' | ').slice(0,500));
console.error=oe;process.exit(0);
